import { AI_PROVIDER_DEFINITIONS } from "../shared/constants.mjs";

const providers = AI_PROVIDER_DEFINITIONS.map((provider) => [provider.id, provider.name]);

function escapeHtml(value) {
  return String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character],
  );
}

export function setupPage(session, returnOrigin) {
  const cards = providers
    .map(
      ([id, label]) =>
        `<article class="provider" data-provider="${id}"><header><span>${escapeHtml(label)}</span><b id="${id}-status">Checking…</b></header><label>API key<input id="${id}-key" type="password" autocomplete="off" placeholder="Paste a new key to add or replace" /></label><label>Model<input id="${id}-model" autocomplete="off" /></label><footer><button data-action="remove" class="secondary">Remove key</button><button data-action="test" class="secondary">Test model</button><button data-action="save">Save</button></footer></article>`,
    )
    .join("");
  const bootstrap = JSON.stringify({ session, returnOrigin });
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ScholarBuddy Mac setup</title>
<style>
:root{color-scheme:light;--ink:#18211d;--muted:#68756d;--line:#d9e2d6;--paper:#f7f9f3;--card:#fff;--accent:#adf064;--deep:#25342c;--warn:#9b4c2f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.45 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:min(1060px,calc(100% - 32px));margin:48px auto 80px}.eyebrow{color:#667d58;font:13px ui-monospace,SFMono-Regular,monospace;letter-spacing:.16em;text-transform:uppercase}h1{max-width:760px;margin:12px 0 8px;font-size:clamp(36px,6vw,68px);line-height:1.02;letter-spacing:-.05em}h1 em{font-style:normal;color:#72964d}.lede{max-width:720px;color:var(--muted);font-size:18px}.notice{margin:24px 0;padding:14px 16px;border:1px solid #cddbc4;border-radius:12px;background:#f0f6e9;color:#4c6041}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:26px}.panel{padding:24px;border:1px solid var(--line);border-radius:18px;background:var(--card);box-shadow:0 12px 35px rgba(31,48,38,.05)}.wide{grid-column:1/-1}h2{margin:0 0 6px;font-size:22px}p{color:var(--muted)}label{display:grid;gap:6px;color:#536159;font-size:13px}input{width:100%;min-height:44px;padding:10px 12px;border:1px solid #cbd6c8;border-radius:9px;background:#fff;color:var(--ink);font:inherit}button{min-height:42px;padding:9px 15px;border:0;border-radius:9px;background:var(--accent);color:#172014;font:700 14px inherit;cursor:pointer}button.secondary{border:1px solid #ced7cc;background:#fff;color:#5c6961}button:disabled{opacity:.55;cursor:wait}.row{display:flex;gap:10px;align-items:end}.row label{flex:1}.provider-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.provider{padding:15px;border:1px solid #e0e6de;border-radius:12px;background:#fbfcf9}.provider header,.provider footer,.check{display:flex;justify-content:space-between;align-items:center;gap:10px}.provider header{margin-bottom:12px}.provider header span{font-weight:750}.provider header b,.check b{font-size:12px;color:var(--muted)}.provider header b.ok,.check b.ok{color:#4e7d35}.provider label+label{margin-top:9px}.provider footer{margin-top:12px;justify-content:flex-end}.checks{display:grid;gap:9px;margin-top:16px}.check{padding:12px;border:1px solid #e0e6de;border-radius:10px}.check span{display:grid}.check small{color:var(--muted)}.finish{display:flex;justify-content:space-between;align-items:center;gap:20px}.finish button{min-width:210px;min-height:50px;font-size:16px}.message{min-height:24px;margin:16px 0 0;color:#4e7d35}.message.error{color:var(--warn)}@media(max-width:760px){main{margin-top:28px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.provider-grid{grid-template-columns:1fr}.row,.finish{align-items:stretch;flex-direction:column}.finish button{width:100%}}
</style></head><body><main><span class="eyebrow">Local research bridge</span><h1>Set up ScholarBuddy <em>on this Mac.</em></h1><p class="lede">Keys and research paths stay on this computer. The hosted site receives connection status and the work you explicitly request—never your saved credentials.</p><div class="notice">This page is served by your local Bridge at 127.0.0.1. Close it when setup is complete.</div>
<div class="grid"><section class="panel wide"><h2>AI providers</h2><p>Add only the services you use. On macOS, keys are stored in Keychain and cannot be read back by this page. Testing sends one short request and does not save your changes.</p><div class="provider-grid">${cards}</div></section>
<section class="panel"><h2>Obsidian vault</h2><p>ScholarBuddy writes its Markdown records inside a <strong>ScholarBuddy</strong> folder in the selected vault.</p><div class="row"><label>Vault path<input id="vault" placeholder="/Users/name/Documents/My Vault" /></label><button id="choose-vault" class="secondary">Choose folder</button></div><button id="save-vault" style="margin-top:12px">Save vault</button></section>
<section class="panel"><h2>Local connections</h2><p>Keep Zotero Desktop open. Calendar permission is requested only when you test it.</p><div class="checks"><div class="check"><span><strong>Zotero Desktop</strong><small>Local API · 127.0.0.1:23119</small></span><b id="zotero-status">Checking…</b></div><div class="check"><span><strong>Obsidian</strong><small>Selected vault access</small></span><b id="obsidian-status">Checking…</b></div><div class="check"><span><strong>macOS Calendar</strong><small>Read and write with system permission</small></span><button id="test-calendar" class="secondary">Test permission</button></div></div></section>
<section class="panel wide finish"><div><h2>Connect the browser</h2><p>Open ${escapeHtml(returnOrigin)} in this browser and redeem a five-minute pairing code automatically.</p></div><button id="finish">Finish and open ScholarBuddy</button></section></div><p id="message" class="message" role="status"></p></main>
<script>
const bootstrap=${bootstrap};
const providerIds=${JSON.stringify(providers.map(([id]) => id))};
const message=document.getElementById("message");
function say(text,error=false){message.textContent=text;message.classList.toggle("error",error)}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set("X-ScholarBuddy-Setup",bootstrap.session);if(options.body)headers.set("Content-Type","application/json");const response=await fetch(path,{...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Setup request failed.");return body}
function status(id,connected,label){const node=document.getElementById(id);node.textContent=label||(connected?"Connected":"Setup needed");node.classList.toggle("ok",Boolean(connected))}
async function refresh(){try{const state=await api("/setup/state");document.getElementById("vault").value=state.obsidian.path||"";status("zotero-status",state.zotero.connected,state.zotero.connected?(state.zotero.version||"Connected"):"Not detected");status("obsidian-status",state.obsidian.connected);for(const id of providerIds){const item=state.providers[id];status(id+"-status",item.configured,item.configured?"Configured":"Not configured");document.getElementById(id+"-model").value=item.model||""}}catch(error){say(error.message,true)}}
for(const card of document.querySelectorAll(".provider")){const provider=card.dataset.provider;const apiKeyInput=document.getElementById(provider+"-key");const modelInput=document.getElementById(provider+"-model");const testButton=card.querySelector('[data-action="test"]');for(const input of [apiKeyInput,modelInput])input.addEventListener("input",()=>{testButton.textContent="Test model"});testButton.addEventListener("click",async()=>{testButton.disabled=true;testButton.textContent="Testing…";try{const result=await api("/setup/test/provider",{method:"POST",body:JSON.stringify({provider,apiKey:apiKeyInput.value,model:modelInput.value})});testButton.textContent="Available ✓";say(result.model+" is available for this API key.")}catch(error){testButton.textContent="Try again";say(error.message,true)}finally{testButton.disabled=false}});card.querySelector('[data-action="save"]').addEventListener("click",async()=>{try{await api("/setup/provider",{method:"POST",body:JSON.stringify({provider,apiKey:apiKeyInput.value,model:modelInput.value})});apiKeyInput.value="";say("Provider settings saved securely.");await refresh()}catch(error){say(error.message,true)}});card.querySelector('[data-action="remove"]').addEventListener("click",async()=>{try{await api("/setup/provider",{method:"DELETE",body:JSON.stringify({provider})});say("Provider key removed.");await refresh()}catch(error){say(error.message,true)}})}
document.getElementById("choose-vault").addEventListener("click",async()=>{try{const result=await api("/setup/vault-picker",{method:"POST",body:"{}"});document.getElementById("vault").value=result.path;say("Folder selected. Choose Save vault to use it.")}catch(error){say(error.message,true)}});
document.getElementById("save-vault").addEventListener("click",async()=>{try{await api("/setup/config",{method:"POST",body:JSON.stringify({vaultPath:document.getElementById("vault").value})});say("Obsidian vault saved.");await refresh()}catch(error){say(error.message,true)}});
document.getElementById("test-calendar").addEventListener("click",async(event)=>{const button=event.currentTarget;button.disabled=true;button.textContent="Testing…";try{await api("/setup/test/calendar",{method:"POST",body:"{}"});button.textContent="Connected";say("Calendar permission is ready.")}catch(error){button.textContent="Try again";say(error.message,true)}finally{button.disabled=false}});
document.getElementById("finish").addEventListener("click",async()=>{try{const result=await api("/setup/pair",{method:"POST",body:JSON.stringify({returnOrigin:bootstrap.returnOrigin})});location.href=result.url}catch(error){say(error.message,true)}});
refresh();
</script></body></html>`;
}
